/*
 * realworld api test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Contact: contact@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UserData struct for UserData
type UserData struct {
	Email string `json:"email,omitempty"`
	Token string `json:"token,omitempty"`
	Username string `json:"username,omitempty"`
	Bio string `json:"bio,omitempty"`
	Image string `json:"image,omitempty"`
}
