/*
 * realworld api test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Contact: contact@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Errors struct for Errors
type Errors struct {
	Errors ErrorsErrors `json:"errors,omitempty"`
}
