/*
 * realworld api test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Contact: contact@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ErrorsErrors struct for ErrorsErrors
type ErrorsErrors struct {
	Body []string `json:"body,omitempty"`
}
