openapi: 3.0.0
servers: []
info:
  title: Mail Platform API
  version: 0.0.1
  description: |
    Mail Platform API
    # Beyond OpenAPI
    [Reference](reference.html) for API which cannot modeled after OpenAPI.
tags:
  - name: Initialize
  - name: Auth
  - name: Domain
  - name: Host
  - name: Account
  - name: Group
  - name: Role
  - name: Search
  - name: Message
  - name: Store
  - name: Filter
  - name: License
  - name: Log
  - name: SMTP
  - name: Delivery
  - name: Update
  - name: Audit
  - name: Quarantine
  - name: Report
  - name: System
  - name: Preference
  - name: FunctionControl
  - name: Cryptograph
  - name: User
x-tagGroups:
  - name: Endpoints
    tags:
      - Initialize
      - Auth
      - Domain
      - Host
      - Account
      - Group
      - Role
      - Search
      - Message
      - Store
      - Filter
      - License
      - Log
      - SMTP
      - Delivery
      - Update
      - Audit
      - Quarantine
      - Report
      - System
      - Preference
      - FunctionControl
      - Cryptograph
      - User
paths:
  /initialize:
    $ref: 'path_initialize.yaml#/~1initialize'
  /login:
    $ref: 'path_auth.yaml#/~1login'
  /logout:
    $ref: 'path_auth.yaml#/~1logout'
  /change-password:
    $ref: 'path_auth.yaml#/~1change-password'
