/**
 * realworld api test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.AuthReq
import org.openapitools.client.model.Errors
import org.openapitools.client.model.RegistReq
import org.openapitools.client.model.UserRes
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object DefaultApi {

  def apply(baseUrl: String = "http://localhost:8080/api") = new DefaultApi(baseUrl)
}

class DefaultApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : UserRes (success)
   *   code 422 : Errors (error)
   * 
   * @param authReq 
   */
  def authentication(authReq: Option[AuthReq] = None): ApiRequest[UserRes] =
    ApiRequest[UserRes](ApiMethods.POST, baseUrl, "/users/login", "application/json")
      .withBody(authReq)
      .withSuccessResponse[UserRes](200)
      .withErrorResponse[Errors](422)
      

  /**
   * Expected answers:
   *   code 200 : UserRes (success)
   *   code 422 : Errors (error)
   * 
   * @param registReq 
   */
  def registration(registReq: Option[RegistReq] = None): ApiRequest[UserRes] =
    ApiRequest[UserRes](ApiMethods.POST, baseUrl, "/users", "application/json")
      .withBody(registReq)
      .withSuccessResponse[UserRes](200)
      .withErrorResponse[Errors](422)
      

  /**
   * Expected answers:
   *   code 200 : UserRes (get currentUser)
   */
  def userGet(): ApiRequest[UserRes] =
    ApiRequest[UserRes](ApiMethods.GET, baseUrl, "/user", "application/json")
      .withSuccessResponse[UserRes](200)
      



}

