/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MassMailPreventionConfig (
  enabled: Option[Boolean] = None,
  /* default is outbound. */
  direction: Option[Seq[MailFlowDirection]] = None,
  /* duration of detection rule, in minute */
  duration: Option[Int] = None,
  ipThreshold: Option[Int] = None,
  senderThreshold: Option[Int] = None,
  subjectThreshold: Option[Int] = None,
  expiryUnit: Option[String] = None,
  expiry: Option[Int] = None,
  action: Option[MassMailPreventionReaction] = None,
  authedAction: Option[MassMailPreventionReaction] = None
) extends ApiModel


