/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.Error
import org.openapitools.client.model.InlineObject
import org.openapitools.client.model.InlineObject1
import org.openapitools.client.model.InlineResponse200
import org.openapitools.client.model.Success
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object AuthApi {

  def apply(baseUrl: String = "http://localhost") = new AuthApi(baseUrl)
}

class AuthApi(baseUrl: String) {
  
  /**
   * Change password for a user by their email
   * 
   * Expected answers:
   *   code 200 : Success (Success)
   *   code 400 : Error (error: 3, 1001, 1035, 1036, 1037, 1038, 1039, 1040, 1041)
   * 
   * @param inlineObject1 
   */
  def changePasswordPost(inlineObject1: Option[InlineObject1] = None): ApiRequest[Success] =
    ApiRequest[Success](ApiMethods.POST, baseUrl, "/change-password", "application/json")
      .withBody(inlineObject1)
      .withSuccessResponse[Success](200)
      .withErrorResponse[Error](400)
      

  /**
   * Login
   * 
   * Expected answers:
   *   code 200 : InlineResponse200 (Success)
   *   code 400 : Error (error: 3, 12, 13)
   * 
   * @param inlineObject 
   */
  def loginPost(inlineObject: InlineObject): ApiRequest[InlineResponse200] =
    ApiRequest[InlineResponse200](ApiMethods.POST, baseUrl, "/login", "application/json")
      .withBody(inlineObject)
      .withSuccessResponse[InlineResponse200](200)
      .withErrorResponse[Error](400)
      

  /**
   * Logout
   * 
   * Expected answers:
   *   code 200 :  (Success)
   *   code 400 : Error (error: 6)
   */
  def logoutPost(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, baseUrl, "/logout", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Error](400)
      



}

