/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.Error
import org.openapitools.client.model.FlakeId
import org.openapitools.client.model.InitialData
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object InitializeApi {

  def apply(baseUrl: String = "http://localhost") = new InitializeApi(baseUrl)
}

class InitializeApi(baseUrl: String) {
  
  /**
   * Create default domain and system administrator account.
   * 
   * Expected answers:
   *   code 200 : FlakeId (Success)
   *   code 400 : Error (error: 10, 1006, 1007, 1014, 1015, 6017)
   * 
   * @param initialData domain to be added
   */
  def initializePut(initialData: InitialData): ApiRequest[FlakeId] =
    ApiRequest[FlakeId](ApiMethods.PUT, baseUrl, "/initialize", "application/json")
      .withBody(initialData)
      .withSuccessResponse[FlakeId](200)
      .withErrorResponse[Error](400)
      



}

