/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.Error
import org.openapitools.client.model.RevisionBasedMassMailPreventionConfig
import org.openapitools.client.model.RevisionBasedThreatBehavior
import org.openapitools.client.model.Success
import org.openapitools.client.model.UNKNOWN_BASE_TYPE
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object DomainApi {

  def apply(baseUrl: String = "http://localhost") = new DomainApi(baseUrl)
}

class DomainApi(baseUrl: String) {
  
  /**
   * Update mass mail prevention configuration
   * 
   * Expected answers:
   *   code 200 : Success (Success)
   *   code 400 : Error (error: 8, 9)
   * 
   * @param uNKNOWNBASETYPE 
   * @param domainId Id of domain
   */
  def domainDomainIdMassMailPost(uNKNOWNBASETYPE: UNKNOWN_BASE_TYPE, domainId: String): ApiRequest[Success] =
    ApiRequest[Success](ApiMethods.POST, baseUrl, "/domain/{domain_id}/mass-mail", "application/json")
      .withBody(uNKNOWNBASETYPE)
      .withPathParam("domain_id", domainId)
      .withSuccessResponse[Success](200)
      .withErrorResponse[Error](400)
      

  /**
   * Update domain specific threat behavior settings
   * 
   * Expected answers:
   *   code 200 :  (Success)
   * 
   * @param uNKNOWNBASETYPE 
   * @param domainId Id of domain
   */
  def domainDomainIdThreatBehavior(uNKNOWNBASETYPE: UNKNOWN_BASE_TYPE, domainId: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, baseUrl, "/domain/{domain_id}/threat/behavior", "application/json")
      .withBody(uNKNOWNBASETYPE)
      .withPathParam("domain_id", domainId)
      .withSuccessResponse[Unit](200)
      



}

