/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.Error
import org.openapitools.client.model.Success
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object SystemApi {

  def apply(baseUrl: String = "http://localhost") = new SystemApi(baseUrl)
}

class SystemApi(baseUrl: String) {
  
  /**
   * Rerun index by index error event
   * 
   * Expected answers:
   *   code 200 : Success (Success)
   *   code 400 : Error (error: 8, 9)
   * 
   * @param body Index error type
   * @param messageId Id of a message
   */
  def systemIndexErrorsMessageIdReindexPost(body: Any, messageId: String): ApiRequest[Success] =
    ApiRequest[Success](ApiMethods.POST, baseUrl, "/system/index-errors/{message_id}/reindex", "application/json")
      .withBody(body)
      .withPathParam("message_id", messageId)
      .withSuccessResponse[Success](200)
      .withErrorResponse[Error](400)
      

  /**
   * Delete index error event
   * 
   * Expected answers:
   *   code 200 : Success (Success)
   *   code 400 : Error (error: 8, 9)
   * 
   * @param body Index error type
   * @param messageId Id of a message
   */
  def systemIndexErrorsPost(body: Any, messageId: String): ApiRequest[Success] =
    ApiRequest[Success](ApiMethods.POST, baseUrl, "/system/index-errors/{message_id}/delete", "application/json")
      .withBody(body)
      .withPathParam("message_id", messageId)
      .withSuccessResponse[Success](200)
      .withErrorResponse[Error](400)
      

  /**
   * Rerun index by a message id
   * 
   * Expected answers:
   *   code 200 : Success (Success)
   *   code 400 : Error (error: 8, 9)
   * 
   * @param body Reparse index request
   * @param messageId Id of a message
   */
  def systemReindexMessageIdPoat(body: Any, messageId: String): ApiRequest[Success] =
    ApiRequest[Success](ApiMethods.POST, baseUrl, "/system/reindex/{message_id}", "application/json")
      .withBody(body)
      .withPathParam("message_id", messageId)
      .withSuccessResponse[Success](200)
      .withErrorResponse[Error](400)
      



}

