/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AsyncExportJobInfo (
  owner: Option[String] = None,
  state: Option[AsyncExportJobInfoEnums.State] = None,
  target: Option[String] = None,
  message: Option[String] = None,
  current: Option[Double] = None,
  total: Option[Double] = None,
  id: Option[String] = None,
  startTime: Option[Int] = None,
  endTime: Option[Int] = None
) extends ApiModel

object AsyncExportJobInfoEnums {

  type State = State.Value
  object State extends Enumeration {
    val NONE = Value("NONE")
    val FAILED = Value("FAILED")
    val INPROGRESS = Value("IN_PROGRESS")
    val SUCCESS = Value("SUCCESS")
    val ABORTED = Value("ABORTED")
  }

}

