/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MailParserConfig (
  /* whether limit using SMTP message size, this is pure flag for frontend noting, has no effect on server. */
  usingSmtpMessageSize: Boolean,
  /* parser extraction limit in bytes */
  extractLimit: Int,
  /* files limit in a single archiving file attachment */
  filesInArchiveLimit: Int,
  /* single attachment parsing timeout */
  attachmentParsingTimeoutSecond: Int
) extends ApiModel


