/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MessageEnvelopeShortAttributesMeta (
  time: Option[Int] = None,
  date: Option[Int] = None,
  ip: Option[String] = None,
  hostname: Option[String] = None,
  size: Option[Int] = None,
  blockCause: Option[String] = None,
  comment: Option[String] = None,
  bcc: Option[Seq[String]] = None,
  recipientCount: Option[Int] = None,
  processNodes: Option[Seq[MessageEnvelopeShortAttributesMetaProcessNodes]] = None,
  sourceTag: Option[String] = None,
  importInfo: Option[MessageEnvelopeShortAttributesMetaImportInfo] = None,
  smtpTxId: Option[String] = None
) extends ApiModel


