/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ScopedPreferenceWithKey (
  key: Option[String] = None,
  value: Option[Any] = None,
  scope: Option[ScopedPreferenceWithKeyEnums.Scope] = None,
  resolution: Option[ScopedPreferenceWithKeyEnums.Resolution] = None
) extends ApiModel

object ScopedPreferenceWithKeyEnums {

  type Scope = Scope.Value
  type Resolution = Resolution.Value
  object Scope extends Enumeration {
    val User = Value("user")
    val Domain = Value("domain")
    val System = Value("system")
  }

  object Resolution extends Enumeration {
    val `Override` = Value("override")
    val Fallback = Value("fallback")
    val Intact = Value("intact")
  }

}

