/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class SmtpConfig (
  boundAddresses: Option[String] = None,
  connectionBackLog: Option[Int] = None,
  connectionLimit: Option[Int] = None,
  connectionLimitPerIp: Option[Int] = None,
  connectionTimeout: Option[Int] = None,
  authorizedAddresses: Option[String] = None,
  authRequired: Option[SmtpConfigEnums.AuthRequired] = None,
  verifyIdentity: Option[Boolean] = None,
  maxMessageSize: Option[Int] = None,
  addressBracketsEnforcement: Option[Boolean] = None,
  heloEnforcement: Option[Boolean] = None,
  useStartTls: Option[Boolean] = None,
  useSsl: Option[Boolean] = None,
  handlers: Option[Seq[SmtpConfigHandlers]] = None
) extends ApiModel

object SmtpConfigEnums {

  type AuthRequired = AuthRequired.Value
  object AuthRequired extends Enumeration {
    val `True` = Value("true")
    val `False` = Value("false")
    val Announce = Value("announce")
  }

}

