/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class SystemSyncFailuresError (
  policyId: Option[String] = None,
  error: Option[SystemSyncFailuresErrorEnums.Error] = None
) extends ApiModel

object SystemSyncFailuresErrorEnums {

  type Error = Error.Value
  object Error extends Enumeration {
    val `18000` = Value("18000")
    val `18001` = Value("18001")
    val `18002` = Value("18002")
    val `18003` = Value("18003")
    val `18004` = Value("18004")
    val `18005` = Value("18005")
    val `18006` = Value("18006")
    val `18007` = Value("18007")
    val `18008` = Value("18008")
    val `18009` = Value("18009")
    val `18010` = Value("18010")
    val `18011` = Value("18011")
    val `18012` = Value("18012")
    val `18013` = Value("18013")
    val `18014` = Value("18014")
    val `18015` = Value("18015")
    val `18016` = Value("18016")
    val `18017` = Value("18017")
    val `18018` = Value("18018")
    val `18019` = Value("18019")
    val `18020` = Value("18020")
    val `18021` = Value("18021")
    val `18022` = Value("18022")
    val `18023` = Value("18023")
    val `18024` = Value("18024")
    val `18025` = Value("18025")
    val `18026` = Value("18026")
    val `18027` = Value("18027")
    val `18028` = Value("18028")
  }

}

