/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ThreatBehavior (
  notice: Option[ThreatBehaviorEnums.Notice] = None,
  replaceUrl: Option[ThreatBehaviorEnums.ReplaceUrl] = None,
  resendable: Option[Boolean] = None
) extends ApiModel

object ThreatBehaviorEnums {

  type Notice = Notice.Value
  type ReplaceUrl = ReplaceUrl.Value
  object Notice extends Enumeration {
    val Quarantine = Value("quarantine")
    val Threat = Value("threat")
    val Disabled = Value("disabled")
  }

  object ReplaceUrl extends Enumeration {
    val Disabled = Value("disabled")
    val Threat = Value("threat")
    val All = Value("all")
  }

}

