/**
 * Swagger Petstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.Error2
import org.openapitools.client.model.Pet2
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object PetsApi {

  def apply(baseUrl: String = "http://petstore.swagger.io/v1") = new PetsApi(baseUrl)
}

class PetsApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 201 :  (Null response)
   *   code 0 : Error2 (unexpected error)
   */
  def createPets(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, baseUrl, "/pets", "application/json")
      .withSuccessResponse[Unit](201)
      .withDefaultErrorResponse[Error2]
      

  /**
   * Expected answers:
   *   code 200 : Seq[Pet2] (A paged array of pets)
   *              Headers :
   *                x-next - A link to the next page of responses
   *   code 0 : Error2 (unexpected error)
   * 
   * @param limit How many items to return at one time (max 100)
   */
  def listPets(limit: Option[Int] = None): ApiRequest[Seq[Pet2]] =
    ApiRequest[Seq[Pet2]](ApiMethods.GET, baseUrl, "/pets", "application/json")
      .withQueryParam("limit", limit)
      .withSuccessResponse[Seq[Pet2]](200)
      .withDefaultErrorResponse[Error2]
      
  object ListPetsHeaders {
    def xNext(r: ApiReturnWithHeaders) = r.getStringHeader("x-next")
  }

  /**
   * Expected answers:
   *   code 200 : Seq[Pet2] (Expected response to a valid request)
   *   code 0 : Error2 (unexpected error)
   * 
   * @param petId The id of the pet to retrieve
   */
  def showPetById(petId: String): ApiRequest[Seq[Pet2]] =
    ApiRequest[Seq[Pet2]](ApiMethods.GET, baseUrl, "/pets/{petId}", "application/json")
      .withPathParam("petId", petId)
      .withSuccessResponse[Seq[Pet2]](200)
      .withDefaultErrorResponse[Error2]
      



}

