/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DeliverySetting (
  isDebug: Option[Boolean] = None,
  /* an Integer for the number of times an attempt is made to deliver a particular mail. */
  maxRetries: Option[Int] = None,
  delayTimes: Option[Seq[Int]] = None,
  /* socket read timeout value in milliseconds. This timeout is implemented by java.net.Socket. Default is infinite timeout. */
  smtpTimeout: Option[Int] = None,
  /* if set to true, and a message has some valid and some invalid addresses, send the message anyway, reporting the partial failure with a SendFailedException. If set to false (the default), the message is not sent to any of the recipients if there is an invalid recipient address. */
  sendPartial: Option[Boolean] = None,
  /* socket connection timeout value in milliseconds. This timeout is implemented by java.net.Socket. Default is infinite timeout. */
  connectionTimeout: Option[Int] = None,
  gatewayServer: Option[Seq[String]] = None,
  /* username used for simple authentication */
  authUser: Option[String] = None,
  /* password used for simple authentication */
  authPass: Option[String] = None,
  /* local address (host name) to bind to when creating the SMTP socket. Defaults to the address picked by the Socket class. Should not normally need to be set, but useful with multi-homed hosts where it's important to pick a particular local address to bind to. */
  bindAddress: Option[String] = None,
  /* extra user-defined javamail session properties */
  defProps: Option[Any] = None,
  /* an Integer for the retry number of times to resolve hostname through DNS. */
  dnsProblemRetry: Option[Int] = None,
  /* a String containing the name used in the SMTP HELO and EHLO commands. */
  heloName: Option[String] = None,
  /* if set to true, the mail will be enqueue with LOW-PRIORITY during retries. */
  usePriority: Option[Boolean] = None,
  /* a Boolean (true/false) indicating whether the STARTTLS command (if supported by the server) to switch the connection to a TLS-protected connection before issuing any login commands. Default is false. */
  startTls: Option[Boolean] = None,
  /* a Boolean (true/false) indicating whether to use SSL to connect and use the SSL port unless explicitly overridden. Default is false. */
  isSslEnable: Option[Boolean] = None
) extends ApiModel


