/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Group (
  name: Option[String] = None,
  parentId: Option[String] = None,
  synchronizeType: Option[GroupEnums.SynchronizeType] = None
) extends ApiModel

object GroupEnums {

  type SynchronizeType = SynchronizeType.Value
  object SynchronizeType extends Enumeration {
    val SyncLdap = Value("sync_ldap")
    val SyncDb = Value("sync_db")
    val Manual = Value("manual")
    val System = Value("system")
  }

}

