/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class InitialDomain (
  name: Option[String] = None,
  company: Option[String] = None,
  contact: Option[String] = None,
  phone: Option[String] = None,
  expireDate: Option[Int] = None,
  language: Option[String] = None,
  userLimit: Option[Int] = None,
  aliasLimit: Option[Int] = None,
  quotaLimit: Option[Int] = None,
  logoUrl: Option[String] = None
) extends ApiModel


