/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MatchString (
  `type`: Option[MatchStringEnums.`Type`] = None,
  quantifier: Option[LogicQuantifier] = None,
  patterns: Option[Seq[String]] = None
) extends ApiModel

object MatchStringEnums {

  type `Type` = `Type`.Value
  object `Type` extends Enumeration {
    val Sender = Value("sender")
    val Recipient = Value("recipient")
    val Subject = Value("subject")
    val AttachName = Value("attach_name")
    val AttachContent = Value("attach_content")
    val Content = Value("content")
  }

}

