/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MatchFlowDirection (
  `type`: Option[MatchFlowDirectionEnums.`Type`] = None,
  quantifier: Option[LogicQuantifier] = None,
  domain: Option[String] = None,
  direction: Option[Seq[MailFlowDirection]] = None
) extends ApiModel

object MatchFlowDirectionEnums {

  type `Type` = `Type`.Value
  object `Type` extends Enumeration {
    val FlowDirection = Value("flow_direction")
  }

}

