/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MessageEnvelope (
  sender: Option[MessageEnvelopeSender] = None,
  recipient: Option[MessageEnvelopeSender] = None,
  status: Option[MessageEnvelopeEnums.Status] = None,
  shortAttributes: Option[MessageEnvelopeShortAttributes] = None
) extends ApiModel

object MessageEnvelopeEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Sent = Value("Sent")
    val Quarantined = Value("Quarantined")
    val Discarded = Value("Discarded")
    val Delayed = Value("Delayed")
    val Bounced = Value("Bounced")
    val Imported = Value("Imported")
  }

}

