/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class SearchResultSourceMessage (
  messageId: String,
  from: String,
  to: String,
  cc: String,
  date: String,
  subject: String,
  attachment: SearchResultSourceMessageAttachment,
  parseLimitExceeded: Boolean,
  /* Error codes of encountered exceptions during mail parsing. Known error codes: Exceptional: 1 */
  parseError: Seq[Int]
) extends ApiModel


