/**
 * Mail Platform API
 * Mail Platform API # Beyond OpenAPI [Reference](reference.html) for API which cannot modeled after OpenAPI. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class SynchronizeOption (
  removeNonExists: Option[Boolean] = None,
  /* username in the list will not be removed even if this user is no longer exists in ldap server. */
  ignoreRemoveList: Option[Seq[String]] = None,
  /* username in the list will not be imported during ldap synchronization. */
  ignoreSyncList: Option[Seq[String]] = None
) extends ApiModel


